############################################################
# Project Metadata
# Manages the hole project metadata
############################################################
group=de.leycm.fluxpipe
artifact=flux
prefix=flx
version=1.0.0

authors=[leycm;Lennard;leycm@proton.me]
description=A simple Java library for internationalization and localization of labels and messages in applications.
remote=https://github.com/leycm/fluxpipe

version-catalog=gradle/libs.versions.toml
version-java=21